repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
    -   id: black
-   repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        types: [file, python]
-   repo: https://github.com/nbQA-dev/nbQA
    rev: 1.3.1
    hooks:
    -   id: nbqa-black
    -   id: nbqa-pyupgrade
        args: [--py37-plus]
    -   id: nbqa-isort
    -   id: nbqa-flake8
