name: unsl_erisk_2022
channels:
  - pytorch
  - conda-forge
dependencies:
  - gensim=3.8
  - jupyter=1.0
  - matplotlib=3.1.3
  - numpy=1.18.1
  - pandas=1.0.3
  - python=3.7
  - flake8
  - cudatoolkit=10.1
  - scikit-learn=0.22
  - seaborn=0.10
  - pytorch
  - torchvision=0.6.0
  - torchtext
  - tensorboard
  - lxml
  - wordcloud
  - pip
  - pip:
    - textblob
    - nltk
    - transformers
    - pyss3
    - arviz
    - httpx
