name: unsl_erisk_2022
channels:
  - pytorch
  - conda-forge
dependencies:
  - cudatoolkit=10.1
  - gensim=3.8
  - jupyter=1.0
  - lxml
  - matplotlib=3.1.3
  - numpy=1.18.1
  - pandas=1.0.3
  - pip
  - pre-commit
  - python=3.7
  - pytorch=1.7.1
  - tensorboard
  - torchtext=0.6.0
  - scikit-learn=0.22
  - seaborn=0.10
  - wordcloud
  - pip:
    - arviz
    - httpx
    - nltk
    - pyss3
    - textblob
    - transformers
